In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as  plt
import seaborn as sns
import nltk
import json
from sklearn.model_selection import train_test_split 

In [2]:
data = []
with open(r"C:\Users\Atharva Kulkarni\Desktop\WPI_Courses\Semester-2\NLP\Final_project\archive (2)\yelp_academic_dataset_review.json", 'r', encoding='utf-8') as file:
    for line in file:
        data.append(json.loads(line))

In [3]:
df = pd.DataFrame(data)

In [4]:
df.head()

review_id                 user_id             business_id  \
0  KU_O5udG6zpxOg-VcAEodg  mh_-eMZ6K5RLWhZyISBhwA  XQfwVwDr-v0ZS3_CbbE5Xw   
1  BiTunyQ73aT9WBnpR9DZGw  OyoGAe7OKpv6SyGZT5g77Q  7ATYjTIgM3jUlt4UM3IypQ   
2  saUsX_uimxRlCVr67Z4Jig  8g_iMtfSiwikVnbP2etR0A  YjUWPpI6HXG530lwP-fb2A   
3  AqPFMleE6RsU23_auESxiA  _7bHUi9Uuf5__HHc_Q8guQ  kxX2SOes4o-D3ZQBkiMRfA   
4  Sx8TMOWLNuJBWer-0pcmoA  bcjbaE6dDog4jkNY91ncLQ  e4Vwtrqf-wpJfwesgvdgxQ   

   stars  useful  funny  cool  \
0    3.0       0      0     0   
1    5.0       1      0     1   
2    3.0       0      0     0   
3    5.0       1      0     1   
4    4.0       1      0     1   

                                                text                 date  
0  If you decide to eat here, just be aware it is...  2018-07-07 22:09:11  
1  I've taken a lot of spin classes over the year...  2012-01-03 15:28:18  
2  Family diner. Had the buffet. Eclectic assortm...  2014-02-05 20:30:30  
3  Wow!  Yummy, different,  delicious.   Our favo...  2015-01-04 00:01:03  
4  Cute interior and owner (?) gave us tour of up...  2017-01-14 20:54:15

In [5]:
yelp_reviews = pd.DataFrame()

In [6]:
yelp_reviews['text'] = df['text']
yelp_reviews['stars'] = df['stars']

In [7]:
yelp_reviews.head()

text  stars
0  If you decide to eat here, just be aware it is...    3.0
1  I've taken a lot of spin classes over the year...    5.0
2  Family diner. Had the buffet. Eclectic assortm...    3.0
3  Wow!  Yummy, different,  delicious.   Our favo...    5.0
4  Cute interior and owner (?) gave us tour of up...    4.0

In [8]:
yelp_reviews.isnull().sum()

text     0
stars    0
dtype: int64

In [9]:
yelp_reviews.shape

(6990280, 2)

In [10]:
yelp_reviews['stars'].value_counts()

stars
5.0    3231627
4.0    1452918
1.0    1069561
3.0     691934
2.0     544240
Name: count, dtype: int64

In [11]:
def label_to_score(score):
    if score >= 3:
        return 1
    else:
        return 0

In [12]:
yelp_reviews['stars'] = yelp_reviews['stars'].apply(lambda x: label_to_score(x))

In [13]:
yelp_reviews['stars'].value_counts()

stars
1    5376479
0    1613801
Name: count, dtype: int64

In [14]:
positive_data = yelp_reviews[yelp_reviews["stars"] == 1]
positive_data = positive_data.iloc[:1613801, :]
positive_data.shape

(1613801, 2)

In [15]:
negative_data = yelp_reviews[yelp_reviews["stars"] == 0]
negative_data.shape

(1613801, 2)

In [16]:
yelp_reviews = pd.concat([positive_data, negative_data], axis = 0)
yelp_reviews.head()

text  stars
0  If you decide to eat here, just be aware it is...      1
1  I've taken a lot of spin classes over the year...      1
2  Family diner. Had the buffet. Eclectic assortm...      1
3  Wow!  Yummy, different,  delicious.   Our favo...      1
4  Cute interior and owner (?) gave us tour of up...      1

In [17]:
yelp_reviews = yelp_reviews.sample(frac=1).reset_index(drop=True)
yelp_reviews.head()

text  stars
0  One of the best burgers I've had! Highly recom...      1
1  Had an issue with AC unit and Climate Pros was...      1
2  Ordered from Uber eats and when my bagged orde...      0
3  Alex wanted to check out a new brewery so he h...      1
4  I don't have a lot to say. But let it be known...      1

In [18]:
yelp_reviews.shape

(3227602, 2)

In [18]:
from sklearn.model_selection import train_test_split 

In [23]:
extra_data, main_data = train_test_split(yelp_reviews, test_size = 0.1, random_state=42)

In [24]:
main_data.to_csv("main_data.csv", index = False)

In [2]:
main_data = pd.read_csv(r"C:\Users\Atharva Kulkarni\Desktop\WPI_Courses\Semester-2\NLP\Final_project\main_data.csv")

In [3]:
extra_data, downsized_data = train_test_split(main_data, test_size=0.6, random_state=42)

In [4]:
downsized_data.head()

text  stars
155417  New improved Otts is really nice! It's still r...      1
186018  It his hotel was great! I loved the location! ...      1
127989  I am rarely disappointed with the beer selecti...      1
124810  I was warned not to come to this Subway and I ...      0
85592   Walked in to watch a hockey game...bartender n...      0

In [5]:
downsized_data = downsized_data.reset_index(drop=True)
downsized_data.head()

text  stars
0  New improved Otts is really nice! It's still r...      1
1  It his hotel was great! I loved the location! ...      1
2  I am rarely disappointed with the beer selecti...      1
3  I was warned not to come to this Subway and I ...      0
4  Walked in to watch a hockey game...bartender n...      0

In [6]:
downsized_data.shape

(193657, 2)

In [7]:
downsized_data.stars.value_counts()

stars
1    97033
0    96624
Name: count, dtype: int64

In [8]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer, SnowballStemmer

In [9]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to C:\Users\Atharva
[nltk_data]     Kulkarni\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Atharva
[nltk_data]     Kulkarni\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Atharva
[nltk_data]     Kulkarni\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Atharva Kulkarni\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to C:\Users\Atharva
[nltk_data]     Kulkarni\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [10]:
stop_words = set(stopwords.words('english'))
wordnet_lem = WordNetLemmatizer()
eng_stems = SnowballStemmer('english')

In [11]:
def Data_Cleaning(text):
    tokens = word_tokenize(text.lower())
    removed_stopwords = [word for word in tokens if (not word in stop_words) and (word.isalpha())]
    lemmas = [wordnet_lem.lemmatize(word) for word in removed_stopwords]
    stems = [eng_stems.stem(word) for word in lemmas]
    return stems

In [12]:
downsized_data = downsized_data.reset_index(drop=True)

In [13]:
downsized_data.head()

text  stars
0  New improved Otts is really nice! It's still r...      1
1  It his hotel was great! I loved the location! ...      1
2  I am rarely disappointed with the beer selecti...      1
3  I was warned not to come to this Subway and I ...      0
4  Walked in to watch a hockey game...bartender n...      0

In [14]:
downsized_data['text'] = downsized_data['text'].apply(Data_Cleaning)

In [15]:
downsized_data.head()

text  stars
0  [new, improv, ott, realli, nice, still, realli...      1
1  [hotel, great, love, locat, free, shuttl, plac...      1
2  [rare, disappoint, beer, select, even, bit, pi...      1
3  [warn, come, subway, went, subway, much, poten...      0
4  [walk, watch, hockey, game, bartend, nasti, he...      0

In [16]:
downsized_data["text"] = downsized_data['text'].apply(lambda x: " ".join(x))

In [17]:
downsized_data.head()

text  stars
0  new improv ott realli nice still realli jersey...      1
1  hotel great love locat free shuttl place withi...      1
2  rare disappoint beer select even bit picki alw...      1
3  warn come subway went subway much potenti espe...      0
4  walk watch hockey game bartend nasti hell cust...      0

In [18]:
downsized_data.to_csv("pre_processed.csv", index=False)

In [19]:
downsized_data = pd.read_csv(r"C:\Users\Atharva Kulkarni\Desktop\WPI_Courses\Semester-2\NLP\Final_project\pre_processed.csv")

In [20]:
downsized_data.dropna(inplace = True)

In [21]:
downsized_data = downsized_data.reset_index(drop=True)

In [22]:
downsized_data.shape

(193648, 2)

In [23]:
x_train, x_test, y_train, y_test = train_test_split(downsized_data['text'], downsized_data['stars'], test_size=0.2, random_state=42)

In [24]:
print("X train:", x_train.shape)
print("X test:", x_test.shape)
print("Y train:", y_train.shape)
print("Y test:", y_test.shape)

X train: (154918,)
X test: (38730,)
Y train: (154918,)
Y test: (38730,)


In [71]:
x_train.to_csv('X_Train.csv', index=False)
y_train.to_csv('Y_Train.csv', index=False)
x_test.to_csv('X_Test.csv', index=False)
y_test.to_csv('Y_Test.csv', index=False)

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, classification_report
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

In [9]:
tfidf_vect = TfidfVectorizer()

In [10]:
x_train = tfidf_vect.fit_transform(x_train)
x_test = tfidf_vect.transform(x_test)

In [27]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB

***Naive Bayes***

In [28]:
nb = MultinomialNB(alpha=0.2)

In [67]:
nb_model = nb.fit(x_train, y_train)

In [68]:
nb_train_results = nb_model.predict(x_train)

In [69]:
nb_tfidf_train_acc = accuracy_score(nb_train_results, y_train)
nb_tfidf_train_acc*100

88.1174761981604

In [70]:
nb_test_results = nb_model.predict(x_test)

In [71]:
nb_tfidf_test_acc = accuracy_score(nb_test_results, y_test)
nb_tfidf_test_acc*100

86.33687906640503

In [72]:
nb_tfidf_conf = confusion_matrix(nb_test_results, y_test)
nb_tfidf_conf

array([[16660,  2592],
       [ 2700, 16780]], dtype=int64)

In [73]:
nb_report = classification_report(nb_test_results, y_test)
print(nb_report)

              precision    recall  f1-score   support

           0       0.86      0.87      0.86     19252
           1       0.87      0.86      0.86     19480

    accuracy                           0.86     38732
   macro avg       0.86      0.86      0.86     38732
weighted avg       0.86      0.86      0.86     38732



***Grid Search Naive Bayes***

In [75]:
pipeline = Pipeline([('clf', MultinomialNB())])

In [97]:
parameters = {'clf__alpha': np.arange(0.1, 2, 0.1)}

In [100]:
grid_search = GridSearchCV(pipeline, parameters, cv=10, n_jobs=-1)
grid_search.fit(x_train, y_train)

GridSearchCV(cv=10, estimator=Pipeline(steps=[('clf', MultinomialNB())]),
             n_jobs=-1,
             param_grid={'clf__alpha': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9])})

In [102]:
best_model = grid_search.best_estimator_
test_accuracy = best_model.score(x_test, y_test)
test_accuracy*100

86.44531653413199

***Bernoulli Naive Bayes***

In [82]:
bnb = BernoulliNB()

In [84]:
bnb_model = bnb.fit(x_train, y_train)

In [85]:
bnb_train_results = bnb_model.predict(x_train)

In [88]:
bnb_train_acc = accuracy_score(bnb_train_results, y_train)
bnb_train_acc*100

81.47748910763272

In [87]:
bnb_test_results = bnb_model.predict(x_test)

In [90]:
bnb_test_acc = accuracy_score(bnb_test_results, y_test)
bnb_test_acc*100

80.94856965816379

In [91]:
bnb_conf_matrix = confusion_matrix(bnb_test_results, y_test)
bnb_conf_matrix

array([[14175,  2194],
       [ 5185, 17178]], dtype=int64)

In [92]:
bnb_classification_report = classification_report(bnb_test_results, y_test)
print(bnb_classification_report)

              precision    recall  f1-score   support

           0       0.73      0.87      0.79     16369
           1       0.89      0.77      0.82     22363

    accuracy                           0.81     38732
   macro avg       0.81      0.82      0.81     38732
weighted avg       0.82      0.81      0.81     38732



***Random Forest***

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf = RandomForestClassifier()

In [103]:
rf_model = rf.fit(x_train, y_train)

In [104]:
rf_train_results = rf_model.predict(x_train)

In [106]:
rf_train_acc = accuracy_score(rf_train_results, y_train)
rf_train_acc*100

99.99741810553495

In [108]:
rf_test_results = rf_model.predict(x_test)

In [109]:
rf_test_acc = accuracy_score(rf_test_results, y_test)
rf_test_acc*100

88.96519673654859

***Decision Tree***

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [101]:
dt = DecisionTreeClassifier(criterion='entropy', splitter='random', max_depth=200, min_samples_leaf=75)

In [102]:
dt_model= dt.fit(x_train, y_train)

In [103]:
dt_train_results = dt_model.predict(x_train)

In [104]:
dt_train_acc = accuracy_score(dt_train_results, y_train)
dt_train_acc*100

82.53011270478576

In [105]:
dt_test_results = dt_model.predict(x_test)

In [106]:
dt_test_acc = accuracy_score(dt_test_results, y_test)
dt_test_acc*100

81.59308029950942

In [107]:
dt_conf_mat = confusion_matrix(dt_test_results, y_test)
dt_conf_mat

array([[15929,  3520],
       [ 3609, 15672]], dtype=int64)

In [108]:
dt_classification_report = classification_report(dt_test_results, y_test)
print(dt_classification_report)

              precision    recall  f1-score   support

           0       0.82      0.82      0.82     19449
           1       0.82      0.81      0.81     19281

    accuracy                           0.82     38730
   macro avg       0.82      0.82      0.82     38730
weighted avg       0.82      0.82      0.82     38730



***XgBoost***

In [34]:
import xgboost as xgb

In [35]:
xgboost = xgb.XGBClassifier()

In [13]:
xgb_model = xgboost.fit(x_train, y_train)

In [14]:
xgb_train_results = xgb_model.predict(x_train)

In [15]:
xgb_train_acc = accuracy_score(xgb_train_results, y_train)
xgb_train_acc*100

91.83438980622006

In [16]:
xgb_test_result = xgb_model.predict(x_test)

In [17]:
xgb_test_acc = accuracy_score(xgb_test_result, y_test)
xgb_test_acc*100

89.5145881745417

In [18]:
xgb_conf_mat = confusion_matrix(xgb_test_result, y_test)
xgb_conf_mat

array([[17601,  2124],
       [ 1937, 17068]], dtype=int64)

In [19]:
xgb_classification_report = classification_report(xgb_test_result, y_test)
print(xgb_classification_report)

              precision    recall  f1-score   support

           0       0.90      0.89      0.90     19725
           1       0.89      0.90      0.89     19005

    accuracy                           0.90     38730
   macro avg       0.90      0.90      0.90     38730
weighted avg       0.90      0.90      0.90     38730



## Bag of Words: 

In [8]:
! pip install xgboost


In [39]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

# Create Bag of Words representation
vectorizer = CountVectorizer()
x_train_bow = vectorizer.fit_transform(x_train)
x_test_bow = vectorizer.transform(x_test)



In [40]:
# Naive Bayes
naive_bayes = MultinomialNB()
naive_bayes.fit(x_train_bow, y_train)
nb_pred = naive_bayes.predict(x_test_bow)
print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_pred))
print("Naive Bayes Classification Report:")
print(classification_report(y_test, nb_pred))

Naive Bayes Accuracy: 0.8531887425768139
Naive Bayes Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.82      0.85     19538
           1       0.83      0.88      0.86     19192

    accuracy                           0.85     38730
   macro avg       0.85      0.85      0.85     38730
weighted avg       0.85      0.85      0.85     38730



In [41]:
# Bernoulli Naive Bayes
bernoulli_nb = BernoulliNB()
bernoulli_nb.fit(x_train_bow, y_train)
bnb_pred = bernoulli_nb.predict(x_test_bow)
print("Bernoulli Naive Bayes Accuracy:", accuracy_score(y_test, bnb_pred))
print("Bernoulli Naive Bayes Classification Report:")
print(classification_report(y_test, bnb_pred))

Bernoulli Naive Bayes Accuracy: 0.8086238058352698
Bernoulli Naive Bayes Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.73      0.79     19538
           1       0.76      0.89      0.82     19192

    accuracy                           0.81     38730
   macro avg       0.82      0.81      0.81     38730
weighted avg       0.82      0.81      0.81     38730



In [42]:
# Random Forest
random_forest = RandomForestClassifier()
random_forest.fit(x_train_bow, y_train)
rf_pred = random_forest.predict(x_test_bow)
print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))
print("Random Forest Classification Report:")
print(classification_report(y_test, rf_pred))

Random Forest Accuracy: 0.8889491350374387
Random Forest Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.91      0.89     19538
           1       0.90      0.87      0.89     19192

    accuracy                           0.89     38730
   macro avg       0.89      0.89      0.89     38730
weighted avg       0.89      0.89      0.89     38730



In [43]:
# Decision Tree
decision_tree = DecisionTreeClassifier()
decision_tree.fit(x_train_bow, y_train)
dt_pred = decision_tree.predict(x_test_bow)
print("Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))
print("Decision Tree Classification Report:")
print(classification_report(y_test, dt_pred))

Decision Tree Accuracy: 0.804570100697134
Decision Tree Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.80      0.81     19538
           1       0.80      0.81      0.80     19192

    accuracy                           0.80     38730
   macro avg       0.80      0.80      0.80     38730
weighted avg       0.80      0.80      0.80     38730



In [46]:
# XGBoost
xgboost = xgb.XGBClassifier()
xgboost.fit(x_train_bow, y_train)
xgb_pred = xgboost.predict(x_test_bow)
print("XGBoost Accuracy:", accuracy_score(y_test, xgb_pred))
print("XGBoost Classification Report:")
print(classification_report(y_test, xgb_pred))

XGBoost Accuracy: 0.8966692486444616
XGBoost Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.90      0.90     19538
           1       0.90      0.89      0.90     19192

    accuracy                           0.90     38730
   macro avg       0.90      0.90      0.90     38730
weighted avg       0.90      0.90      0.90     38730



***Word2Vec***

In [47]:
from gensim.models import Word2Vec

In [48]:
# Tokenize text data and train Word2Vec model
word2vec_model = Word2Vec(sentences=[nltk.word_tokenize(text) for text in x_train], vector_size=100, window=5, min_count=1)

In [49]:
# Define a function to convert text to Word2Vec embeddings
def word2vec_transform(text, model):
    vectors = []
    for word in nltk.word_tokenize(text):
        if word in model.wv:
            vectors.append(model.wv[word])
    if len(vectors) == 0:
        return np.zeros(100)  # Return zero vector if no words found
    return np.mean(vectors, axis=0)  # Return mean vector of all words

In [50]:
# Convert text data to Word2Vec embeddings
x_train_w2v = np.array([word2vec_transform(text, word2vec_model) for text in x_train])
x_test_w2v = np.array([word2vec_transform(text, word2vec_model) for text in x_test])

***Decision Tree Word2Vec***

In [51]:
# Decision Tree with Word2Vec
dt_w2v = DecisionTreeClassifier(criterion='entropy', splitter='random', max_depth=200, min_samples_leaf=75)
dt_w2v_model = dt_w2v.fit(x_train_w2v, y_train)
dt_w2v_train_results = dt_w2v_model.predict(x_train_w2v)

In [52]:
dt_w2v_train_acc = accuracy_score(dt_w2v_train_results, y_train)
print("Decision Tree Training Accuracy with Word2Vec:", dt_w2v_train_acc * 100)

Decision Tree Training Accuracy with Word2Vec: 84.54020836829807


In [53]:
dt_w2v_test_results = dt_w2v_model.predict(x_test_w2v)
dt_w2v_test_acc = accuracy_score(dt_w2v_test_results, y_test)
print("Decision Tree Testing Accuracy with Word2Vec:", dt_w2v_test_acc * 100)

Decision Tree Testing Accuracy with Word2Vec: 83.7722695584818


In [54]:
dt_w2v_conf_mat = confusion_matrix(dt_w2v_test_results, y_test)
print("Decision Tree Confusion Matrix with Word2Vec:\n", dt_w2v_conf_mat)

Decision Tree Confusion Matrix with Word2Vec:
 [[16489  3236]
 [ 3049 15956]]


In [55]:
dt_w2v_classification_report = classification_report(dt_w2v_test_results, y_test)
print("Decision Tree Classification Report with Word2Vec:\n", dt_w2v_classification_report)

Decision Tree Classification Report with Word2Vec:
               precision    recall  f1-score   support

           0       0.84      0.84      0.84     19725
           1       0.83      0.84      0.84     19005

    accuracy                           0.84     38730
   macro avg       0.84      0.84      0.84     38730
weighted avg       0.84      0.84      0.84     38730



***XGBoost with Word2Vec***

In [56]:
# XGBoost with Word2Vec
xgb_w2v = xgb.XGBClassifier()
xgb_w2v_model = xgb_w2v.fit(x_train_w2v, y_train)
xgb_w2v_train_results = xgb_w2v_model.predict(x_train_w2v)

In [57]:
xgb_w2v_train_acc = accuracy_score(xgb_w2v_train_results, y_train)
print("XGBoost Training Accuracy with Word2Vec:", xgb_w2v_train_acc * 100)

XGBoost Training Accuracy with Word2Vec: 93.82770239739733


In [58]:
xgb_w2v_test_result = xgb_w2v_model.predict(x_test_w2v)
xgb_w2v_test_acc = accuracy_score(xgb_w2v_test_result, y_test)
print("XGBoost Testing Accuracy with Word2Vec:", xgb_w2v_test_acc * 100)

XGBoost Testing Accuracy with Word2Vec: 89.89672088820036


In [59]:
xgb_w2v_conf_mat = confusion_matrix(xgb_w2v_test_result, y_test)
print("XGBoost Confusion Matrix with Word2Vec:\n", xgb_w2v_conf_mat)

XGBoost Confusion Matrix with Word2Vec:
 [[17700  2075]
 [ 1838 17117]]


In [60]:
xgb_w2v_classification_report = classification_report(xgb_w2v_test_result, y_test)
print("XGBoost Classification Report with Word2Vec:\n", xgb_w2v_classification_report)

XGBoost Classification Report with Word2Vec:
               precision    recall  f1-score   support

           0       0.91      0.90      0.90     19775
           1       0.89      0.90      0.90     18955

    accuracy                           0.90     38730
   macro avg       0.90      0.90      0.90     38730
weighted avg       0.90      0.90      0.90     38730



***Naive Bayes with Word2Vec***

In [61]:
# Naive Bayes with Word2Vec (Note: MultinomialNB is not suitable for Word2Vec)
from sklearn.naive_bayes import GaussianNB

nb_w2v = GaussianNB()
nb_w2v_model = nb_w2v.fit(x_train_w2v, y_train)
nb_w2v_train_results = nb_w2v_model.predict(x_train_w2v)
nb_w2v_train_acc = accuracy_score(nb_w2v_train_results, y_train)
print("Naive Bayes with Word2Vec Training Accuracy:", nb_w2v_train_acc)

Naive Bayes with Word2Vec Training Accuracy: 0.7959565705728192


In [62]:
nb_w2v_test_results = nb_w2v_model.predict(x_test_w2v)
nb_w2v_test_acc = accuracy_score(nb_w2v_test_results, y_test)
print("Naive Bayes with Word2Vec Test Accuracy:", nb_w2v_test_acc)

Naive Bayes with Word2Vec Test Accuracy: 0.7999483604441002


***Bernoulli Naive Bayes***

In [63]:
# Bernoulli Naive Bayes with Word2Vec
bnb_w2v = BernoulliNB()
bnb_w2v_model = bnb_w2v.fit(x_train_w2v, y_train)
bnb_w2v_train_results = bnb_w2v_model.predict(x_train_w2v)

In [64]:
bnb_w2v_train_acc = accuracy_score(bnb_w2v_train_results, y_train)
print("Bernoulli Naive Bayes Training Accuracy with Word2Vec:", bnb_w2v_train_acc * 100)

Bernoulli Naive Bayes Training Accuracy with Word2Vec: 78.63063039801702


In [65]:
bnb_w2v_test_results = bnb_w2v_model.predict(x_test_w2v)
bnb_w2v_test_acc = accuracy_score(bnb_w2v_test_results, y_test)
print("Bernoulli Naive Bayes Testing Accuracy with Word2Vec:", bnb_w2v_test_acc * 100)

Bernoulli Naive Bayes Testing Accuracy with Word2Vec: 79.01368448231345


In [66]:
bnb_w2v_conf_matrix = confusion_matrix(bnb_w2v_test_results, y_test)
print("Bernoulli Naive Bayes Confusion Matrix with Word2Vec:\n", bnb_w2v_conf_matrix)

Bernoulli Naive Bayes Confusion Matrix with Word2Vec:
 [[15434  4024]
 [ 4104 15168]]


In [67]:
bnb_w2v_classification_report = classification_report(bnb_w2v_test_results, y_test)
print("Bernoulli Naive Bayes Classification Report with Word2Vec:\n", bnb_w2v_classification_report)

Bernoulli Naive Bayes Classification Report with Word2Vec:
               precision    recall  f1-score   support

           0       0.79      0.79      0.79     19458
           1       0.79      0.79      0.79     19272

    accuracy                           0.79     38730
   macro avg       0.79      0.79      0.79     38730
weighted avg       0.79      0.79      0.79     38730



***Random Forest Word2vec***

In [68]:
# Random Forest with Word2Vec
rf_w2v = RandomForestClassifier()
rf_w2v_model = rf_w2v.fit(x_train_w2v, y_train)
rf_w2v_train_results = rf_w2v_model.predict(x_train_w2v)

In [69]:
rf_w2v_train_acc = accuracy_score(rf_w2v_train_results, y_train)
print("Random Forest Training Accuracy with Word2Vec:", rf_w2v_train_acc * 100)

Random Forest Training Accuracy with Word2Vec: 99.99806349165364


In [70]:
rf_w2v_test_results = rf_w2v_model.predict(x_test_w2v)
rf_w2v_test_acc = accuracy_score(rf_w2v_test_results, y_test)
print("Random Forest Testing Accuracy with Word2Vec:", rf_w2v_test_acc * 100)

Random Forest Testing Accuracy with Word2Vec: 88.52569067906016
